[tool.poetry]
name = "silver_spectacle"
version = "0.1.0"
description = ""
authors = ["Jeff Hykin <jeff.hykin@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.7,<3.10"
pip = "20.1.1"
python-include = "1.0.0"
ez_yaml = "1.1.0"
PyYAML = "5.4.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
